### ISSUE TITLE
Feature request:  add CRD for service catalog entry

### ISSUE THREAD

**Issue by jcogilvie** [DataDog/datadog-operator#940] opened 2023-10-04 15:35 UTC
The operator should be able to populate our service catalog via `ServiceCatalogEntry` (or the like) CRDs deployed in our app manifests.

**Comment by demolitionmode** [comment] 2024-05-30 19:22
Is this a duplicate of https://github.com/DataDog/datadog-operator/issues/761?

**Comment by jcogilvie** [comment] 2024-05-30 20:05
Appears so. They're both me. I guess I either forgot or couldn't find the old one!

**Closed** 2024-05-30 20:05 UTC
Labels: feature request
