### ISSUE TITLE
remoteconfiguration feature supported?

### ISSUE THREAD

**Issue by cookiesowns** [DataDog/datadog-operator#885] opened 2023-08-03 22:40 UTC
# Remote Configuration feature

It appears the docs have been updated for the datadogagent spec to support `feature.remoteConfiguration.enabled` config.

However even after deploying the latest 1.1.0 rc build, the `datadogagent` CRD does not appear to have a type for `spec.features.remoteConfiguration`

**Comment by celenechang** [comment] 2023-08-04 01:40
Hi @cookiesowns - I'm not able to reproduce the issue you reported. Do you mind sharing the operator image (which RC?), the error message, as well as the DatadogAgent manifest? Thank you.

**Comment by jeffreyflynt** [comment] 2023-08-06 06:42
@cookiesowns I have it enabled in mine by following this example: https://github.com/DataDog/datadog-operator/blob/main/examples/datadogagent/v2alpha1/datadog-agent-with-remote-configuration.yaml

**Comment by levan-m** [comment] 2023-10-16 21:44
Resolving since we haven't received any update for over a month. Feel free to reopen if you are still facing same issue.

**Closed by levan-m** 2023-10-16 21:44 UTC
Labels: question
