### ISSUE TITLE
Running OpenShift 4.12.4, Kubernetes 1.25 - memory issue

### ISSUE THREAD

**Issue by walter-heestermans-toyota** [DataDog/datadog-operator#750] opened 2023-04-05 07:52 UTC
There was a ticket for related issues, but with OpenShift 4.12.4, running k8s 1.25, I still see issues.

containerStatuses:

```
containerID: cri-o://e6c571d656632f9cf700588cf32dd16c25ed55e225f3b2f628c4eb013b740f4d
image: gcr.io/datadoghq/operator:1.0.0-rc.12
imageID: gcr.io/datadoghq/operator@sha256:2e138eebbe37a2640b1899d49eee10a6d1535d75ee55c1d16daa7794635ef34e
lastState:
terminated:
containerID: cri-o://7dfe3846c596e8b17d3483136d4d301e5c7bc41e5fc667ec51d177545f09e265
exitCode: 2
finishedAt: "2023-04-03T14:23:38Z"
reason: Error
startedAt: "2023-04-03T14:22:04Z"
name: datadog-operator

```
{"level":"INFO","ts":"2023-04-03T14:23:38Z","logger":"DatadogMetricForwarders","msg":"Got Datadog Site","CustomResource.Namespace":"datadog-agent","CustomResource.Name":"datadog","site":"https://api.datadoghq.com"}
{"level":"ERROR","ts":"2023-04-03T14:23:38Z","logger":"klog","msg":"Observed a panic: \"invalid memory address or nil pointer dereference\" (runtime error: invalid memory address or nil pointer dereference)\ngoroutine 771 [running]:\nk8s.io/apimachinery/pkg/util/runtime.logPanic({0x19600c0?, 0x2ce8cb0})\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/runtime/runtime.go:74 +0x86\nk8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x73?})\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/runtime/runtime.go:48 +0x75\npanic({0x19600c0, 0x2ce8cb0})\n\t/usr/local/go/src/runtime/panic.go:838 +0x207\ngithub.com/DataDog/datadog-operator/pkg/controller/utils/datadog.(*metricsForwarder).getCredentialsV2(0xc000525310?, 0xc0005251e0)\n\t/workspace/pkg/controller/utils/datadog/metrics_forwarder.go:611 +0x69\ngithub.com/DataDog/datadog-operator/pkg/controller/utils/datadog.(*metricsForwarder).setupV2(0xc0000f5340)\n\t/workspace/pkg/controller/utils/datadog/metrics_forwarder.go:261 +0x24f\ngithub.com/DataDog/datadog-operator/pkg/controller/utils/datadog.(*metricsForwarder).connectToDatadogAPI(0xc0000f5340)\n\t/workspace/pkg/controller/utils/datadog/metrics_forwarder.go:303 +0x58\nk8s.io/apimachinery/pkg/util/wait.ConditionFunc.WithContext.func1({0x18, 0xc000060800})\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:220 +0x1b\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext({0x1e8b9e0?, 0xc000815200?}, 0xc00006ddd0?)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:233 +0x57\nk8s.io/apimachinery/pkg/util/wait.poll({0x1e8b9e0, 0xc000815200}, 0x10?, 0xf4af85?, 0xc000716880?)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:580 +0x38\nk8s.io/apimachinery/pkg/util/wait.PollImmediateUntilWithContext({0x1e8b9e0, 0xc000815200}, 0x10?, 0xc000060800?)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:545 +0x49\nk8s.io/apimachinery/pkg/util/wait.PollImmediateUntil(0xc0000f5340?, 0xc00057cf60?, 0x0?)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:536 +0x7c\ngithub.com/DataDog/datadog-operator/pkg/controller/utils/datadog.(*metricsForwarder).start(0xc0000f5340, 0x0?)\n\t/workspace/pkg/controller/utils/datadog/metrics_forwarder.go:165 +0x10c\ncreated by github.com/DataDog/datadog-operator/pkg/controller/utils/datadog.(*ForwardersManager).Register\n\t/workspace/pkg/controller/utils/datadog/forwarders_manager.go:69 +0x365\n"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13e58a9]

goroutine 771 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x73?})
        /go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/runtime/runtime.go:55 +0xd8
panic({0x19600c0, 0x2ce8cb0})
        /usr/local/go/src/runtime/panic.go:838 +0x207
github.com/DataDog/datadog-operator/pkg/controller/utils/datadog.(*metricsForwarder).getCredentialsV2(0xc000525310?, 0xc0005251e0)
        /workspace/pkg/controller/utils/datadog/metrics_forwarder.go:611 +0x69
github.com/DataDog/datadog-operator/pkg/controller/utils/datadog.(*metricsForwarder).setupV2(0xc0000f5340)
        /workspace/pkg/controller/utils/datadog/metrics_forwarder.go:261 +0x24f
github.com/DataDog/datadog-operator/pkg/controller/utils/datadog.(*metricsForwarder).connectToDatadogAPI(0xc0000f5340)
        /workspace/pkg/controller/utils/datadog/metrics_forwarder.go:303 +0x58
k8s.io/apimachinery/pkg/util/wait.ConditionFunc.WithContext.func1({0x18, 0xc000060800})
        /go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:220 +0x1b
k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext({0x1e8b9e0?, 0xc000815200?}, 0xc00006ddd0?)
        /go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:233 +0x57
k8s.io/apimachinery/pkg/util/wait.poll({0x1e8b9e0, 0xc000815200}, 0x10?, 0xf4af85?, 0xc000716880?)
        /go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:580 +0x38
k8s.io/apimachinery/pkg/util/wait.PollImmediateUntilWithContext({0x1e8b9e0, 0xc000815200}, 0x10?, 0xc000060800?)
```

**Comment by CharlyF** [comment] 2023-04-05 12:21
Hi there - Thank you for the report, we are looking into it.

**Comment by levan-m** [comment] 2023-04-05 14:34
This can happen regardless of k8s version and is caused by missing credentials in DatadogAgent `v2alpha1` manifest in this case (based on the line number). 

You may run into this scenario when:
* applying `v2alpha1` manifest without setting `spec.global.credentials`
* applying `v1alpha1` manifest when the stored CRD version of DatadogAgent is `v2alpha1` and webhook isn't enabled. Without webhook `v1alpha1` is serialized to `v2alpha1` and fields that don't map are dropped.

To further assist you, could you please share the version of the Operator you are running, how you installed it (helm chart version and value overrides) and the manifest you are using.

**Comment by levan-m** [comment] 2023-04-19 14:42
Fix for above issue was merged and will be included in the upcoming release, the PR https://github.com/DataDog/datadog-operator/pull/752. 

Since we haven't received any follow-up I'm resolving the issue.

**Closed by levan-m** 2023-04-19 14:42 UTC
Labels: bug, component/controller
